name: "Setup Dart SDK"
description: "Download and setup the Dart SDK."
branding:
  icon: check-circle
  color: blue
inputs:
  sdk:
    description: >-
      This can be either the channel to install (i.e., 'stable', 'beta', 'dev'),
      an SDK release version (i.e., '2.19', '3.1'), or a specific SDK version
      (i.e, '2.19.1', '3.0.0-1.4.beta').
    required: false
    default: "stable"
  architecture:
    description: "The CPU architecture ('x64', 'ia32', 'arm', or 'arm64')."
    required: false
  flavor:
    description: "The build flavor ('release' or 'raw')."
    required: false
  pub-dev-credentials:
    description: >-
      Whether to automatically configure OIDC credentials for pub.dev publishing.
      When 'true' and the workflow has 'id-token: write' permission, this action
      will obtain an OIDC token and configure 'dart pub' to use it for pub.dev.
      Set to 'false' if you use 'id-token: write' for other purposes (e.g., Azure,
      AWS, or GCP OIDC) and don't want pub.dev credentials to be configured.
      This is especially important for self-hosted runners where credentials persist.
    required: false
    default: "true"
outputs:
  dart-version:
    description: 'The installed Dart version.'
runs:
  using: "node20"
  main: "dist/index.mjs"
