name: "Setup Dart SDK"
description: "Download and setup the Dart SDK."
branding:
  icon: check-circle
  color: blue
inputs:
  sdk:
    description: >-
      This can be either the channel to install (i.e., 'stable', 'beta', 'dev'),
      a wildcard format for the latest patch release (i.e., `2.19.x`, `3.1.x`),
      or a specific sdk version to install (i.e, '2.19.1', '3.0.0-1.4.beta').
      Using one of the named channels instead of a version will give you the
      latest version published of that channel.
    required: false
    default: "stable"
  architecture:
    description: "The CPU architecture ('x64', 'ia32', 'arm', or 'arm64')."
    required: false
  flavor:
    description: "The build flavor ('release' or 'raw')."
    required: false
outputs:
  dart-version:
    description: 'The installed Dart version.'
runs:
  using: "node16"
  main: "dist/index.mjs"
