name: "Setup Dart SDK"
description: "Download and setup the Dart SDK."
branding:
  icon: check-circle
  color: blue
inputs:
  sdk:
    description: >-
      This can be either the channel to install (i.e., 'stable', 'beta', 'dev'),
      an SDK release version (i.e., '2.19', '3.1'), or a specific SDK version
      (i.e, '2.19.1', '3.0.0-1.4.beta').
    required: false
    default: "stable"
  architecture:
    description: "The CPU architecture ('x64', 'ia32', 'arm', or 'arm64')."
    required: false
  flavor:
    description: "The build flavor ('release' or 'raw')."
    required: false
  cache:
    description: "Whether to cache the Dart SDK and the pub cache."
    required: false
    default: true
outputs:
  dart-version:
    description: 'The installed Dart version.'

runs:
  using: composite
  steps:
  - uses: actions/setup-node@v4
    with:
      node-version: 24

  - name: "Run setup"
    id: setup-step
    run: node dist/index.mjs
    shell: bash

  - name: Cache Dart SDK
    if: ${{ inputs.cache == 'true' }}
    id: dart-cache
    uses: actions/cache@v5
    with:
      path: ${{ steps.setup-step.outputs.cache-path }}
      key: ${{ steps.setup-step.outputs.cache-key }}

  - name: Print Cache Status
    if: ${{ inputs.cache == 'true' }}
    run: |
      if [ "${{ steps.dart-cache.outputs.cache-hit }}" == "true" ]; then
        echo "Dart SDK cache hit! 🚀"
        echo "Key used: ${{ steps.setup-step.outputs.cache-key }}"
      else
        echo "Dart SDK cache miss. 📥"
        echo "Could not find cache for key: ${{ steps.setup-step.outputs.cache-key }}"
      fi
    shell: bash