# Validate that the compiled artifacts are up-to-date.

name: Build
permissions:
  contents: read

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at 00:00.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: ./
        with:
          sdk: dev
      - run: dart pub get
      - run: dart analyze --fatal-infos
      - run: dart tool/sig.dart --verify
      - run: npm run build
