name: Publish flutter to pub.dev

## Caller of this workflow should use it as follows:
## jobs:
##   publish:
##     uses: dart-lang/setup-dart/.github/workflows/publish.yml@main [or a recent commit hash / version tag]
##     # with:
##     #   working-directory: path/to/sub/directory

on:
  workflow_call:
    inputs:
      environment:
        description: if specified, the workflow is required to be run in this environment (with additional approvals)
        required: false
        type: string
      working-directory:
        description: directory with-in the repository where the package is located (if not in the repository root)
        required: false
        type: string
      build_runner:
        description: if specified, the workflow will run an additional step of build_runner
        required: false
        type: boolean

jobs:
  publish:
    name: 'Publish to pub.dev'
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: temurin
          java-version: "17"
      - name: Flutter action
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
      - name: Flutter version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ inputs.working-directory }}
      - name: Run build_runner
        if: ${{ inputs.build_runner == 'true' }}
        run: flutter run build_runner build
        working-directory: ${{ inputs.working-directory }}
      - name: Publish - dry run
        run: flutter pub publish --dry-run
        working-directory: ${{ inputs.working-directory }}
      # Publishing...
      - name: Publish to pub.dev
        run: flutter pub publish -f
        working-directory: ${{ inputs.working-directory }}
